import { test, expect } from './member-fixture.js';
const mockMarket = page => page.route('https://s3.tradingview.com/**', route => route.fulfill({ contentType: 'text/javascript', body: `(()=>{const s=document.currentScript,c=JSON.parse(s.textContent),f=document.createElement('iframe');f.srcdoc='<body>'+JSON.stringify(c)+'</body>';s.parentElement.querySelector('.tradingview-widget-container__widget').append(f);})();` }));
for (const fallback of [false, true]) test(`Market and chart settings survive terminal moves and reload (fallback ${fallback})`, async ({page}) => {
  await mockMarket(page);
  if (fallback) await page.addInitScript(() => { Element.prototype.moveBefore = undefined; });
  await page.goto('/');
  await page.getByRole('button', {name:'03 Night desk',exact:true}).click();
  await page.locator('#terminal-btn').click();
  const terminal = page.frameLocator('#terminal-mount iframe');
  await terminal.locator('#symbol').selectOption('NASDAQ:AAPL');
  await terminal.getByRole('button', {name:'Line',exact:true}).click();
  await terminal.getByRole('button', {name:'MA',exact:true}).click();
  await page.locator('#close-terminal').click();
  const laptop = page.frameLocator('.laptop-display iframe');
  await expect(laptop.locator('#symbol')).toHaveValue('NASDAQ:AAPL');
  await expect(laptop.getByRole('button',{name:'Line',exact:true})).toHaveAttribute('aria-pressed','true');
  await expect(laptop.getByRole('button',{name:'MA',exact:true})).toHaveAttribute('aria-pressed','true');
  await page.reload();
  await expect(laptop.locator('#symbol')).toHaveValue('NASDAQ:AAPL');
  await page.locator('#terminal-btn').click();
  await expect(terminal.locator('#symbol')).toHaveValue('NASDAQ:AAPL');
});
test('Adderall travels, cycles markets and chart settings, pauses, and stops', async ({page}) => {
  const errors=[]; page.on('pageerror',e=>errors.push(e.message));
  await mockMarket(page); await page.goto('/');
  await expect(page.locator('#adderall-btn')).toBeHidden();
  await page.getByRole('button',{name:'03 Night desk',exact:true}).click();
  await page.locator('#adderall-btn').click();
  await expect(page.locator('#adderall-btn')).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#behavior-pill')).toHaveText('Locked in',{timeout:35000});
  const laptop=page.frameLocator('.laptop-display iframe');
  await expect(laptop.locator('#symbol')).toHaveValue('COINBASE:ETHUSD',{timeout:3000});
  await expect(laptop.getByRole('button',{name:'Line',exact:true})).toHaveAttribute('aria-pressed','true',{timeout:4000});
  await expect(laptop.getByRole('button',{name:'MA',exact:true})).toHaveAttribute('aria-pressed','true',{timeout:4000});
  await expect(laptop.locator('#symbol')).toHaveValue('KRAKEN:XMRUSD',{timeout:4000});
  await page.getByRole('button',{name:'Pause virtual world',exact:true}).click();
  const snapshot=await laptop.locator('#symbol').inputValue();
  await page.waitForTimeout(6500);
  await expect(laptop.locator('#symbol')).toHaveValue(snapshot);
  await expect(laptop.locator('#desk-cursor')).toBeHidden();
  await page.getByRole('button',{name:'Resume virtual world',exact:true}).click();
  await expect(laptop.locator('#clear-studies')).toHaveClass(/fly-click/,{timeout:6000});
  await expect(laptop.getByRole('button',{name:'MA',exact:true})).toHaveAttribute('aria-pressed','false');
  await page.screenshot({path:'test-results/desk-focus.png',fullPage:true});
  await page.locator('#adderall-btn').click();
  const stopped=await laptop.locator('#symbol').inputValue();
  await page.waitForTimeout(6500);
  await expect(laptop.locator('#symbol')).toHaveValue(stopped);
  await expect(laptop.locator('#desk-cursor')).toBeHidden();
  expect(errors).toEqual([]);
});
